service: RemindMeOfThisTweet
plugins:
- serverless-dotenv-plugin
- serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs8.10
  logRetentionInDays: 30
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "events:DeleteRule"
    - "events:RemoveTargets"
    - "events:PutRule"
    - "events:PutTargets"
    Resource:
    - "*"

  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_TOKEN_SECRET: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    REDIS_HOSTNAME: ${env:REDIS_HOSTNAME}
    REDIS_PORT: ${env:REDIS_PORT}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    LAMBDA_FUNCTION_NAME: ${env:LAMBDA_FUNCTION_NAME}
    LAMBDA_FUNCTION_ARN: ${env:LAMBDA_FUNCTION_ARN}

package:
  exclude:
  - README.md
  - .gitignore
  - .env
  - .env.example
  - .idea/**
  - .git/**
  - test/**
  - "*.png"

functions:
  fetchTweetsAndSetReminders:
    handler: handler.fetchTweetsAndSetReminders
    events:
    - schedule: rate(1 minute)
  checkForReminders:
    handler: checkForReminders
    events:
    - schedule: rate(1 minute)
  remind:
    handler: handler.remind
  retryFailedTasks:
    handler: handler.retryFailedTasks
